export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const INCREASE_LOADED_ITEMS = 'INCREASE_LOADED_ITEMS';
export const FILTER_OPTION = 'FILTER_OPTION';
export const CLEAR_FILTER_OPTION = 'CLEAR_FILTER_OPTION';
export const DISPLAY_OPTION = 'DISPLAY_OPTION';
